dist: xenial
language: java

jdk:
  - openjdk11

# disable shallow clone so SonarCloud can use SCM history to compute blame data
git:
  depth: false

# the first part of the cache phase happens
# between git checkout and before_install
cache:
  directories:
    - $HOME/.m2/repository

before_install:
  - cp ./settings.xml $HOME/.m2/settings.xml

# the default java install step does
# mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install:
  - mvn install -DskipTests=true -B -V -Psource-quality
# splitting the build into install and test parts gives us a quicker way
# to identify what went wrong
script:
  - mvn verify -B

# before_cache happens before the second part of the cache phase,
# which happens after script
before_cache:
  - rm -rf $HOME/.m2/repository/io/lighty

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

#temp commit
