# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      if: ${{ env.SONAR_TOKEN != 0 }}
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Maven install (skip test)
      run: mvn install -DskipTests=true -B -V -Psource-quality -P docker
    - name: Maven test + SonarCloud
      if: ${{ env.SONAR_TOKEN != 0 }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        -Dsonar.java.source=1.11
        -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
        -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
        -Dsonar.host.url=https://sonarcloud.io
    - name: Maven test no SonarCloud
      if: ${{ env.SONAR_TOKEN == 0 }}
      run: mvn -B verify
    - name: Upload surefire test results
      uses: actions/upload-artifact@v2
      with:
        name: Surefire-Test-Results
        path: ~/**/surefire-reports/**/*.txt
    - name: Install Helm
      run: sudo snap install helm --classic
    - name: Create microk8s cluster
      uses: balchua/microk8s-actions@v0.2.1
      with:
        channel: '1.20/stable'
        addons: '["helm", "proxy"]'
    - name: Init helm
      run: |
        sudo microk8s kubectl create serviceaccount tiller --namespace kube-system
        sudo microk8s kubectl create clusterrolebinding tiller-cluster-rule \
        --clusterrole=cluster-admin \
        --serviceaccount=kube-system:tiller
        sudo microk8s helm init --stable-repo-url https://charts.helm.sh/stable --service-account tiller --wait
    - name: Upload docker image
      run: |
        docker save --output="./lighty-image:latest.tar" lighty-rnc:latest
        sudo microk8s ctr --namespace k8s.io image import lighty-image\:latest.tar
        rm lighty-image:latest.tar
    - name: Deploy app to microk8s cluster
      run: |
        sudo microk8s helm install --name=lighty-rnc \
        lighty-applications/lighty-rnc-app-aggregator/lighty-rnc-app-helm/helm/lighty-rnc-app-helm/
    - name: Lighty-rnc-app get operations health-check
      run: |
        sleep 100  # Wait for app controller to start
        netstat -tlpn
        sudo microk8s kubectl get services
        sudo microk8s kubectl get pods
        curl --user admin:admin -H "Content-Type: application/json" --insecure http://localhost:30888/restconf/operations